### ISSUE TITLE
unable to build image

### ISSUE THREAD

**Issue by kiucheng** [JackGruber/docker_dustcloud#5]
It's my first venture into Docker.....
When I run docker build -t dustcloud . it returned unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Dockerfile: no such file or directory

Any ideas? Thanks

**Comment by JackGruber** [comment]
which operating system?

Can you run ```docker run --rm alpine echo "Hallo Welt"```

**Comment by kiucheng** [comment]
Yes Hello World works. On Hassbian. I have all 3 Dustcloud, myphpadmin and mariadb containers and images

**Comment by JackGruber** [comment]
hm ...

Create a file ```Dockerfile``` with the content ```FROM Alpine``` in a new folder and run ```docker build -t test . ``` in it.

**Comment by JackGruber** [comment]
Are you in the git clone when you execute the command?

**Comment by kiucheng** [comment]
Git clone directory! of course. Now it works. Thanks!
