### ISSUE TITLE
CMDSERVER 

### ISSUE THREAD

**Issue by ufulu** [JackGruber/docker_dustcloud#7]
Hi and thanks first, for putting togehter this docker image. What exactly is the CMDSERVER? Is it the IP of my vacuum? Is it the IP of the docker container running dustcloud? I am currently a little lost. 

Thanks

**Comment by JackGruber** [comment]
Hi,

use for the CMDSERVER the IP address of your docker host, where you can reache the web interface of the dustcloud.
